
[node]
  blockchain_pubkey_str = "037c7ca1e98fb4abe2e7c97132495c8fb525687b3833650d4a96c2dae69c3d01cb"
  blockchain_seckey_str = ""
  create_block_burn_factor = 100
  create_block_max_transaction_size = 134217728
  default_connections = []
  genesis_address_str = "2gnKuyAyVuZAhCSTodAxTbRXboWb67aidBL"
  genesis_coin_volume = 10000000000.0
  genesis_signature_str = "d463b608f4d4990ce041474b8792112c8bbfb347d13c7d11912fd3cd17ef82ef6e1e778517afb8e44bff91c2ed37ae1cb106103def297869f272ddbb650373e701"
  genesis_timestamp = 1426562704
  max_block_size = 134217728
  max_block_transactions_size = 134217728
  peer_list_url = "https://127.0.0.1/peers.txt"
  port = 6000
  unconfirmed_burn_factor = 100
  unconfirmed_max_transaction_size = 134217728
  web_interface_port = 6420

[params]
  distribution_addresses = ["TkyD4wD64UE6M5BkNQA17zaf7Xcg4AufwX", "2PBcLADETphmqWV7sujRZdh3UcabssgKAEB"]
  distribution_addresses_total = 2
  initial_unlocked_count = 2
  max_coin_supply = 100000000.0
  user_burn_factor = 100
  user_max_transaction_size = 134217728
